name: GitHub Actions CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    name: example earthly test
    runs-on: ubuntu-latest
    steps:
      - uses: earthly/actions/setup-earthly@v1
        with:
          version: v0.6.4
      - uses: actions/checkout@v2
      - name: what version is installed?
        run: earthly --version
      - name: Build and Push All Images
        # Make this step dependent on the success of the previous one (ECR credentials)
        if: success()
        run: |
          earthly --push --ci +docker
        working-directory: ./gradle-project
      # Only push latest tags on main branch
      - name: Push All Latest Images
        if: success() && github.ref == 'refs/heads/main'
        run: |
          earthly --push --ci +docker --build-arg container_tag_suffix=""
        working-directory: ./gradle-project
