name: GitHub Actions CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    name: example earthly test
    runs-on: ubuntu-latest
    steps:
      - uses: earthly/actions/setup-earthly@v1
        with:
          version: v0.6.4
      - uses: actions/checkout@v2
      - name: what version is installed?
        run: earthly --version
      - name: run the earthly hello world
        run: earthly +build
        working-directory: ./gradle-project
